services:
  backend:
    build:
      context: ./LinkLite-server
    env_file:
      - ./LinkLite-server/link_lite/.env
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: >
        sh -c "./wait_for_db.sh python /app/link_lite/manage.py migrate 
        && python /app/link_lite/manage.py runserver 0.0.0.0:8000"
    networks:
      - linklite_network
    depends_on:
      - db
  
  frontend:
    build:
      context: ./LinkLite-client
    env_file:
      - ./LinkLite-client/.env
    ports:
      - "3001:80"  
    networks:
      - linklite_network 
    depends_on:
      - backend
  
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - linklite_network

networks:
  linklite_network:
    driver: bridge

volumes:
  db_data: